/*
export const CREATE_TRIP = "CREATE_TRIP";
export const EDIT_TRIP = "EDIT_TRIP";
export const VIEW_TRIP_DETAILS = "VIEW_TRIP_DETAILS";
export const DELETE_TRIP = "DELETE_TRIP";
export const VIEW_ALL_TRIPS = "VIEW_ALL_TRIPS";
*/

export const ACTION_TYPES = {
  CREATE_TRIP: "CREATE_TRIP",
  EDIT_TRIP: "EDIT_TRIP",
  VIEW_TRIP_DETAILS: "VIEW_TRIP_DETAILS",
  DELETE_TRIP: "DELETE_TRIP",
  VIEW_ALL_TRIPS: "VIEW_ALL_TRIPS",
  ADD_TASK: "ADD_TASK",
}
